spring.application.name=api

spring.datasource.url=jdbc:postgresql://crossover.proxy.rlwy.net:14755/railway
spring.datasource.username=postgres
spring.datasource.password=WkfgFvlcLSDNolOqSShjZYGXKKKqgvml

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080